-- Create fun_facts table for displaying random science facts during tests
CREATE TABLE IF NOT EXISTS public.fun_facts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fact_text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.fun_facts ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read fun facts
CREATE POLICY "Anyone can view fun facts"
  ON public.fun_facts
  FOR SELECT
  USING (true);

-- Insert 100 fun facts
INSERT INTO public.fun_facts (fact_text) VALUES
('Lidské tělo obsahuje dostatek uhlíku na výrobu 900 tužek.'),
('DNA ve všech buňkách vašeho těla by se natažená dosáhla až na Pluto a zpět.'),
('Srdce vypumpuje za den přibližně 7 570 litrů krve.'),
('Žaludek si každé 3-4 dny obnoví svou sliznici.'),
('Nervové impulsy cestují rychlostí až 430 km/h.'),
('Lidský mozek spotřebuje 20% celkové energie těla.'),
('Za život projde lidským tělem asi 5 milionů litrů krve.'),
('V ústech máme více bakterií než je lidí na Zemi.'),
('Každý člověk má jedinečný otisk jazyka.'),
('Oční čočka je jediná část těla bez krevního zásobení.'),
('Vaše plíce obsahují přes 300 milionů alveol.'),
('Červené krvinky obíhají tělem za 20 sekund.'),
('Každý člověk má asi 100 000 vlasů na hlavě.'),
('Lidská kůže se kompletně obnoví každých 28 dní.'),
('Mozek generuje až 70 000 myšlenek denně.'),
('Vaše nos dokáže rozlišit přes 1 bilion pachů.'),
('Kosti jsou 5x pevnější než ocel stejné tloušťky.'),
('Lidské ucho dokáže rozlišit přes 400 000 zvuků.'),
('Za život vyprodukujeme až 25 000 litrů slin.'),
('Lidské tělo obsahuje 0,2 mg zlata.'),
('Bílé krvinky žijí jen 13-20 dní.'),
('Játra plní více než 500 různých funkcí.'),
('Vaše oko dokáže rozlišit až 10 milionů barev.'),
('Lidský mozek je aktivnější během spánku než během dne.'),
('Kyslík je ve vodě díky hydrogenové vazbě.'),
('Diamanty a grafit jsou tvořeny stejným prvkem - uhlíkem.'),
('Světlo cestuje rychlostí 299 792 km/s.'),
('Atom je z 99,9999% prázdný prostor.'),
('Voda může existovat ve třech skupenstvích současně.'),
('Helium nikdy nezamrzne za normálního tlaku.'),
('Zlato je tak kujné, že 1 gram lze roztáhnout na 3 km.'),
('Nejchladnější místo ve vesmíru má -272°C.'),
('Blesk je pětkrát teplejší než povrch Slunce.'),
('Sklo je ve skutečnosti přechlazená kapalina.'),
('Vesmír se neustále rozpíná rychlostью větší než světlo.'),
('Černé díry mohou mít miliardy násobek hmotnosti Slunce.'),
('Neutronové hvězdy jsou nejhustší objekty ve vesmíru.'),
('Gravitace je nejslabší ze čtyř základních sil.'),
('Vakuum ve vesmíru není úplně prázdné.'),
('Rychlost zvuku ve vodě je 4x vyšší než ve vzduchu.'),
('Magnet ztrácí své vlastnosti při zahřátí nad Curieovu teplotu.'),
('Elektrony se pohybují téměř rychlostí světla.'),
('Radioaktivní prvky se přirozeně rozpadají.'),
('Supravodivost umožňuje vedení elektřiny bez odporu.'),
('Kvantová provázanost funguje okamžitě na jakoukoliv vzdálenost.'),
('Antimoterie okamžitě anihiluje při kontaktu s hmotou.'),
('Planckova konstanta je nejmenší možná jednotka energie.'),
('Nejmenší částice viditelné pouhým okem jsou 0,1 mm.'),
('Lidské oko může zaznamenat jediný foton světla.'),
('Bakterie dokážou přežít tisíce let zmrazené.'),
('Některé stromy žijí přes 5000 let.'),
('Houby nejsou ani rostliny ani živočichové.'),
('DNA všech lidí je z 99,9% identická.'),
('Mitochondrie mají vlastní DNA.'),
('Lidské tělo obsahuje přibližně 37 bilionů buněk.'),
('Bakterie v našem těle převažují lidské buňky 10:1.'),
('První antibiotikum bylo penicilin objevený 1928.'),
('Viry nejsou považovány za živé organismy.'),
('Některé bakterie dokážou žít v kyselině nebo vroucí vodě.'),
('Rostliny provádějí fotosyntézu pomocí chlorofylu.'),
('Lidská genomová sekvence obsahuje 3 miliardy párů bází.'),
('Evoluční změny mohou nastat během několika generací.'),
('Kvasnice jsou jednobuněčné organismy používané při pečení.'),
('Priony jsou infekční proteiny bez genetického materiálu.'),
('Lidské tělo regeneruje kůži rychleji než jiné tkáně.'),
('Embryonální vývoj u lidí trvá přibližně 38 týdnů.'),
('Geny kontrolují vývoj a funkci všech živých organismů.'),
('Biologická rozmanitost na Zemi zahrnuje miliony druhů.'),
('Ekosystémy recyklují živiny neustálým koloběhem.'),
('Kořeny stromů komunikují přes podzemní mykorrhizu.'),
('Kyslík na Zemi vzniká především z mořských řas.'),
('Lidský mozek dokáže ukládat petabyte dat.'),
('Neurony v mozku komunikují elektrochemickými signály.'),
('Synapse spojují neurony a umožňují přenos informací.'),
('Paměť je uložená v síti neuronálních spojení.'),
('Spánek pomáhá konsolidovat vzpomínky.'),
('Endorfiny jsou přirozenou formou úlevy od bolesti.'),
('Adrenalin zvyšuje srdeční frekvenci během stresu.'),
('Serotonin ovlivňuje náladu a emoce.'),
('Dopamin je spojen s pocitem odměny.'),
('Hypofýza řídí mnoho hormonálních funkcí.'),
('Štítná žláza reguluje metabolismus těla.'),
('Inzulin reguluje hladinu cukru v krvi.'),
('Kortizol je hormon uvolňovaný při stresu.'),
('Melatonin reguluje spánkový cyklus.'),
('Testosteron a estrogen jsou pohlavní hormony.'),
('Lidské tělo obsahuje asi 60% vody.'),
('Ledviny filtrují krev až 50x denně.'),
('Játra dokážou regenerovat až 75% své hmotnosti.'),
('Slezina filtruje staré červené krvinky.'),
('Slinivka břišní produkuje trávicí enzymy.'),
('Imunitní systém chrání tělo před patogeny.'),
('Bílé krvinky jsou klíčové pro obranu organismu.'),
('Antibodies specificky rozpoznávají antigeny.'),
('Vakcinace stimuluje imunitní paměť.'),
('Lymfatický systém odvádí přebytečnou tekutinu z tkání.'),
('Kostní dřeň produkuje nové krevní buňky.'),
('Hemoglobin přenáší kyslík v červených krvinkách.'),
('Krevní plazma obsahuje proteiny a elektrolyty.'),
('Srážení krve zabraňuje nadměrné ztrátě krve.'),
('Krevní tlak je měřen v mmHg.'),
('Arterie nesou okysličenou krev od srdce.'),
('Žíly vracejí odkysličenou krev zpět do srdce.');